accounts/urls.py
from django.urls import path
from . import views
from .views import CustomPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('manage', views.user_manage_view, name='user_manage'),
    path('delete/<int:user_id>',views.user_delete_view, name='user_delete' ),
    path('role_update/<int:user_id>',views.user_role_update_view, name='role_update' ),
    path('invite', views.user_invite, name='user_invite'),
    path('invite/register/', views.invite_register_view, name='invite_register'),   
    path('mypage', views.mypage, name='mypage'),
    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
    path('user_update/',views.user_update_view, name='user_update' ),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('shift_pilot/admin/', admin.site.urls),
    path('',include('portfolio.urls')),
    path('shift_pilot/accounts/', include('accounts.urls')),
    path('shift_pilot/shifts/', include('shifts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shifts/urls.py
from django.urls import path
from . import views

app_name = 'shifts'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('requests/', views.shift_request_view, name='shift_request'),
    path('patterns/', views.shift_pattern_view, name='shift_pattern'),
    path('patterns/delete/<int:pattern_id>/', views.delete_pattern_view, name='delete_pattern'),
    path('pattern_assignment_summaries/', views.pattern_assignment_summary_view, name='pattern_assignment_summaries'),
    path('create/', views.shift_create_view, name='shift_create'),
    path('assign/', views.auto_assign_shifts, name='shifts'),
    path('update-user-shift/', views.update_user_shift, name='update_user_shift'), 
    path("toggle_all_rest/", views.toggle_all_rest, name="toggle_all_rest"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import(
    AbstractBaseUser, PermissionsMixin,BaseUserManager
)
from django.conf import settings
import uuid

class UserManager(BaseUserManager):
        def create_user(self, email, password, **extra_fields):
            if not email:
                raise ValueError('メールアドレスは必須です')
            user = self.model(email=email,**extra_fields)
            user .set_password(password)
            user.save()
            return user
        
        def create_superuser(self, email, password, **extra_fields):
            extra_fields.setdefault('is_staff', True)
            extra_fields.setdefault('is_active', True)
            return self.create_user(email, password, **extra_fields)
        
class Role(models.Model):
    role_name = models.CharField(max_length=128)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.role_name

class Team(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Team{self.id}"
        
class User(AbstractBaseUser, PermissionsMixin):
    name = models.CharField(max_length=128)
    email =  models.EmailField(max_length=128, unique=True)
    password = models.CharField(max_length=128)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    profile_image = models.ImageField(upload_to='profile_images', null=True, blank=True)

    role = models.ForeignKey(Role, on_delete=models.SET_NULL, null=True, blank=True)
    team = models.ForeignKey(Team, on_delete=models.SET_NULL, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    class Meta: 
        db_table = 'user'

class Invitation(models.Model):
    token = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    team = models.ForeignKey('Team', on_delete=models.CASCADE)
    
    created_at = models.DateTimeField(auto_now_add=True)    
    updated_at = models.DateTimeField(auto_now=True)

    is_used = models.BooleanField(default=False)
    invited_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='sent_invitations'
    )

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import PasswordChangeForm

User = get_user_model()

class ProfileImageForm(forms.ModelForm):
    class Meta:
        model  = User
        fields = ['profile_image']
        widgets ={
            'profile_image' : forms.FileInput(attrs={'class': 'form-control d-none' })
        } 

class SignupForm(forms.ModelForm):

    confirm_password = forms.CharField(
        label='パスワード再入力', widget=forms.PasswordInput()
    )
    class Meta:
        model = User
        fields = ('name', 'email', 'password')
        labels = {
            'name': '名前',
            'email': 'メールアドレス',
            'password': 'パスワード',
        }
        widgets ={'password': forms.PasswordInput()}
    

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        if password !=confirm_password:
            self.add_error('confirm_password', 'パスワードが一致しません')
        if password:
            try:
                validate_password(password, self.instance)
            except ValidationError as e:
                self.add_error('password', e)
        return cleaned_data
    
    def save(self, commit=False):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user
    
class LoginForm(forms.Form):
    email = forms.EmailField(label="メールアドレス")
    password = forms.CharField(label="パスワード", widget=forms.PasswordInput())

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('name', 'email')
        labels = {
            'name': '名前',
            'email': 'メールアドレス',
        }
   
class CustomPasswordChangeForm(PasswordChangeForm):
    def clean_new_password1(self):
        new_password1 = self.cleaned_data.get("new_password1")
        old_password = self.cleaned_data.get("old_password")

        if old_password and new_password1 and old_password == new_password1:
            raise ValidationError("元のパスワードと同じパスワードにはできません。")

        return new_password1

accounts/views.py
from django.shortcuts import render, redirect ,get_object_or_404
from .import forms
from .models import Role, Team, Invitation
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.views import PasswordChangeView
from .forms import CustomPasswordChangeForm
from django.contrib.auth import update_session_auth_hash


User = get_user_model()

def signup(request):
    signup_form = forms.SignupForm(request.POST or None)
    if signup_form.is_valid():
        user = signup_form.save(commit=False)
        user.set_password(signup_form.cleaned_data['password'])
        user.is_active = True 
        try:
            user.role = Role.objects.get(role_name="管理者")
        except Role.DoesNotExist:
            user.role = None
        user.is_staff = True
        new_team = Team.objects.create()
        user.team =new_team
        user.save()
        login(request, user) 
        return redirect('shifts:home')
    
    elif request.method == 'POST':
        messages.error(request, "入力内容に不備があります。")

    
    return render(
        request, 'accounts/signup.html',context= {
            'signup_form': signup_form,
            'hide_navbar': True
        }
    )

def user_login(request):
    login_form = forms.LoginForm(request.POST or None)

    if request.method == 'POST':
        if login_form.is_valid():
            email = login_form.cleaned_data['email']
            password = login_form.cleaned_data['password']
            user = authenticate(request, username=email, password=password)
            if user:
                login(request, user)
                return redirect('shifts:home')
            else:
                messages.error(request, "メールアドレスまたはパスワードが正しくありません")
        else:
            messages.error(request, "入力内容に不備があります")


    return render(
        request, 'accounts/user_login.html', context={
            'login_form': login_form,
            'hide_navbar': True
        }
    )

@login_required
def user_logout(request):
    logout(request)
    return redirect('accounts:login') 

@login_required
def user_manage_view(request):
    if not request.user.role or request.user.role.role_name != '管理者':
        return HttpResponseForbidden("このページにはアクセスできません")
    team_users = User.objects.filter(team=request.user.team)
    roles = Role.objects.all()
    context = {
        'team_users': team_users,
        'roles': roles,
    }
    return render(request, 'accounts/user_manage.html', context)

@login_required
def user_delete_view(request,user_id):
    if request.method == 'POST':
        user = get_object_or_404(User, id=user_id)
        user.delete()
        return redirect('accounts:user_manage')
    else:
        return HttpResponseForbidden("不正なアクセスです")
    
@login_required
def user_role_update_view(request,user_id):
    if request.method == 'POST':
        role_id = request.POST.get('role_id')
        user = get_object_or_404(User, id=user_id)
        role = get_object_or_404(Role, id=role_id)
        user.role = role
        user.save()

        if user != request.user:
            messages.success(request, f"{user.name} さんの権限を『{role.role_name}』に変更しました")

        if role.role_name == '一般' and user == request.user:
            messages.info(request, "権限が変更されたため、ホーム画面に戻りました")
            return redirect('shifts:home')
        return redirect('accounts:user_manage')

    return HttpResponseForbidden("不正なアクセスです")
    
@login_required
def user_invite(request):
    if request.method == 'POST':
        invitation = Invitation.objects.create(
            team=request.user.team,
            invited_by=request.user,
        )
        invite_url = request.build_absolute_uri(
            reverse('accounts:invite_register') + f'?token={invitation.token}'
        )
    else:
        invite_url = None
    return render(request, 'accounts/user_invite.html', context={'invite_url': invite_url})

def invite_register_view(request):
    token_str =  request.GET.get('token')
    invitation = get_object_or_404(Invitation, token=token_str)

    if invitation.is_used:
        return HttpResponseForbidden("この招待リンクはすでに使用されています")
    
    form = forms.SignupForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password'])
        user.team = invitation.team
        user.is_active = True

    
        user.role = Role.objects.get(role_name = "一般")
        
        user.save()
        invitation.is_used = True
        invitation.save()
        login(request, user)
        return redirect('shifts:home')
    elif request.method == 'POST':
        messages.error(request, '入力内容に不備があります。')
        
    return render(request, 'accounts/signup.html', {
        'signup_form': form,
        'hide_navbar': True
        })

@login_required
def mypage(request):
    if request.method == 'POST':
        form = forms.ProfileImageForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:mypage')
    else:
        form = forms.ProfileImageForm(instance=request.user)
    return render(
        request, 'accounts/mypage.html', {
            'user': request.user,
            'form' : form,
    })
        
class CustomPasswordChangeView(PasswordChangeView):
    template_name = 'accounts/password_change.html'
    form_class = CustomPasswordChangeForm
    
    def form_valid(self, form):
        user = form.save()
        update_session_auth_hash(self.request, user)
        messages.success(self.request, 'パスワードを変更しました')
        return render(self.request, self.template_name, {'form': form})
    
@login_required
def user_update_view(request):
    if request.method == 'POST':
        form =forms.UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'アカウント情報を変更しました')
            return redirect('accounts:user_update')
        else:
            messages.error(request, '入力内容に不備があります')
    else:
        form = forms.UserUpdateForm(instance=request.user)
    return render(
        request, 'accounts/user_update.html' ,{
            'user': request.user,
            'form': form,
        }
    )

templates/accounts/mypage.html
{% extends "base.html" %}
{% load add_class %}

{% block extra_css %}
<style>
.return-link:hover {
    text-decoration: underline !important;
}
</style>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h5 class="text-secondary ms-1 mb-4">マイページ</h5>
    <div class="row align-items-center">
        <div class = 'col-md-4 text-center'>
            <div class="mb-2">
                {% if user.profile_image %}
                    <img src = "{{ user.profile_image.url }}" 
                        class="rounded-circle mb-3" 
                        width="140" 
                        height="140" 
                        style="object-fit: cover;"
                        alt="プロフィール画像">
                {% else %}
                    <img src="https://cdn-icons-png.flaticon.com/512/847/847969.png"
                        class="rounded-circle mb-3"
                        width="140"
                        height="140"
                        style="object-fit: cover;"
                        alt="">
                {% endif %}
            </div>

            <form method="POST" enctype="multipart/form-data" id="uploadForm">
                {% csrf_token %}
                <label for="id_profile_image" class="form-label text-muted" style="cursor:pointer;">
                    +画像を登録
                </label>
                {{ form.profile_image|add_class:"form-control d-none" }}
            </form>
        </div>
            
        <div class="col-md-8 lh-lg" >
            <h5>アカウント情報</h5>
            <p><strong>ユーザー名：</strong>{{ user.name }}</p>
            <p><strong>メールアドレス：</strong>{{ user.email }}</p>
            <p>
                <strong>パスワード：</strong>
                <a href="{% url 'accounts:password_change' %}" class="text-primary text-decoration-none return-link" >パスワード変更</a>
            </p>
            <p>
                <a href="{% url 'accounts:user_update' %}" class="text-primary text-decoration-none return-link" >アカウント情報変更</a>
            </p>
        </div>
    </div>
</div>
<script>
  document.addEventListener('DOMContentLoaded', function () {
    const fileInput = document.getElementById('id_profile_image');
    if (fileInput) {
      fileInput.addEventListener('change', function () {
        document.getElementById('uploadForm').submit();
      });
    }
  });
</script>
{% endblock %}

templates/accounts/password_change.html
{% extends "base.html" %}
{% load add_class %}
{% block content %}
<style>
.fixed-label {
    display: inline-block;
    min-width: 180px;   
    text-align: right;  
    margin-right: 2rem;  
    white-space: nowrap; 
}
</style>

<div class="container mt-5">
    <h5 class="text-center text-secondary ms-1 mb-4">パスワード変更</h5>
    <div class="d-flex justify-content-center">
        <div style="width: 100%; max-width: 500px; padding: 30px; border-radius: 10px;">

            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="閉じる"></button>
                    </div>
                {% endfor %}
            {% endif %}


            <form method="POST">
                {% csrf_token %}
                {{ form.non_field_errors }}

                <div class="mb-3 d-flex align-items-center">
                    <label for="id_old_password" class="fixed-label text-start">現在のパスワード</label>
                    <div class="flex-grow-1">
                        {{ form.old_password|add_class:"form-control" }}
                        {% for error in form.old_password.errors %}
                            <div class="text-danger small">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>

                <div class="mb-3 d-flex align-items-center">
                    <label for="id_new_password1" class="fixed-label text-start">新しいパスワード</label>
                    <div class="flex-grow-1">
                        {{ form.new_password1|add_class:"form-control" }}
                        {% for error in form.new_password1.errors %}
                            <div class="text-danger small">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>

                <div class="mb-3 d-flex align-items-center">
                    <label for="id_new_password2" class="fixed-label text-start">新しいパスワード（確認用）</label>
                    <div class="flex-grow-1">
                        {{ form.new_password2|add_class:"form-control" }}
                        {% for error in form.new_password2.errors %}
                            <div class="text-danger small">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>

                <div class="text-center mt-3">
                    <button type="submit" class="btn btn-primary px-5">変更</button>
                </div>
            </form> 

        </div>
    </div>
</div>
{% endblock %}

templates/accounts/signup.html
{% extends "base.html" %}
{% load add_class %}

{% block extra_css %}
<style>
.return-link:hover {
    text-decoration: underline !important;
}
.col-form-label {
    white-space: nowrap;
}
</style>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h5 class="text-center text-secondary ms-1 mb-4">新規アカウント登録</h5>
    <div class="d-flex justify-content-center">
        <div style="width: 100%; max-width: 500px; padding: 30px; border-radius: 10px;">

            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="閉じる"></button>
                </div>
              {% endfor %}
            {% endif %}

            <form method="POST">
                {% csrf_token %}
                {{ signup_form.non_field_errors }}
                

                <div class="mb-3 row">
                    <label for="id_name" class="col-sm-4 col-form-label text-start">名前</label>
                    <div class="col-sm-8">
                        {{ signup_form.name|add_class:"form-control" }}
                        {% if signup_form.name.errors %}
                            <div class="text-danger small">{{ signup_form.name.errors.0 }}</div>
                        {% endif %}
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="id_email" class="col-sm-4 col-form-label text-start">メールアドレス</label>
                    <div class="col-sm-8">
                        {{ signup_form.email|add_class:"form-control" }}
                        {% if signup_form.email.errors %}
                            <div class="text-danger small">{{ signup_form.email.errors.0 }}</div>
                        {% endif %}
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="id_password" class="col-sm-4 col-form-label text-start">パスワード</label>
                    <div class="col-sm-8">
                        {{ signup_form.password|add_class:"form-control" }}
                        {% if signup_form.password.errors %}
                            <div class="text-danger small">{{ signup_form.password.errors.0 }}</div>
                        {% endif %}
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="id_confirm_password" class="col-sm-4 col-form-label text-start">パスワード再入力</label>
                    <div class="col-sm-8">
                        {{ signup_form.confirm_password|add_class:"form-control" }}
                        {% if signup_form.confirm_password.errors %}
                            <div class="text-danger small">{{ signup_form.confirm_password.errors.0 }}</div>
                        {% endif %}
                    </div>
                </div>

                <div class="text-center mt-3">
                    <button type="submit" class="btn btn-primary px-5">登録</button>
                </div>
            </form>

            <div class="text-center mt-3">
                <a href="{% url 'accounts:login' %}" class="text-primary text-decoration-none return-link">ログイン画面へ戻る</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/user_invite.html
{% extends "base.html" %}

{% block extra_css %}
<style>
.gray-btn {
    background-color: #dee2e6;
}
.gray-btn:hover,
.gray-btn:focus {
    background-color: #adb5bd;; 
    box-shadow: 0 0 4px rgba(0, 0, 0, 0.2); 
    color: #000;
    border: 1px solid #bbb;
}
.return-link:hover {
    text-decoration: underline !important;
}
</style>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h5 class="text-center  text-secondary ms-1 mb-4">ユーザー招待</h5>

    <div class="d-flex justify-content-center">
        <div style="width: 100%; max-width: 500px;">
            
            <form method="POST" class="text-center mt-3">
                {% csrf_token %}
                <button type="submit" class="btn gray-btn text-dark btn-lg px-5 mb-4">ユーザー招待URLを作成する</button>
            </form>

            {% if invite_url %}
                <input type="text" class="form-control text-center my-3" value="{{ invite_url }}" readonly>
            {% endif %}

            <p class="text-center">※このリンクを招待したいユーザーに送ってください</p>
            <p class="text-center">※リンクは1度利用されると無効になります</p>

            <div class="text-center mt-3">
                <a href="{% url 'accounts:user_manage' %}" class="text-primary text-decoration-none return-link">ユーザー管理画面へ戻る</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/user_login.html
{% extends "base.html" %} 
{% load add_class %}

{% block extra_css %}
<style>
.return-link:hover {
    text-decoration: underline !important;
}
</style>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="d-flex justify-content-center">
        <div style="width: 100%; max-width: 500px; padding: 30px; border-radius: 10px;">
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-danger alert-dismissible fade show text-center">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="閉じる"></button>
                </div>
              {% endfor %}
            {% endif %}
            
            <div class="text-center mb-4">
                <h1>Shift Pilot</h1>
            </div>

            <form method="POST">
                {% csrf_token %}
                {{ login_form.non_field_errors }}

                <div class="mb-3 row">
                    <label for="id_email" class="col-sm-4 col-form-label text-end">メールアドレス</label>
                    <div class="col-sm-8">
                        {{ login_form.email|add_class:"form-control" }}
                        {% if login_form.email.errors %}
                            <div class="text-danger small">{{ login_form.email.errors.0 }}</div>
                        {% endif %}
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="id_password" class="col-sm-4 col-form-label text-end">パスワード</label>
                    <div class="col-sm-8">
                        {{ login_form.password|add_class:"form-control" }}
                        {% if login_form.password.errors %}
                            <div class="text-danger small">{{ login_form.password.errors.0 }}</div>
                        {% endif %}
                    </div>
                </div>

                <div class="text-center mt-3">
                    <button type="submit" class="btn btn-primary px-5">ログイン</button>
                </div>
            </form>

            <div class="text-center mt-3">
                <a href="{% url 'accounts:signup' %}" class="text-primary text-decoration-none return-link">アカウント登録</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/user_manage.html
{% extends "base.html" %}

{% block extra_css %}
<style>
.gray-btn {
    background-color: #dee2e6;
}
.gray-btn:hover,
.gray-btn:focus {
    background-color: #adb5bd;; 
    box-shadow: 0 0 4px rgba(0, 0, 0, 0.2); 
    color: #000;
    border: 1px solid #bbb;
}

.table {
    table-layout: auto !important; 
    width: 100%;
}

.table td, .table th {
    white-space: nowrap !important; 
}

.table select.form-select {
    min-width: 120px;
    white-space: nowrap;
}

.table .btn {
    white-space: nowrap !important;
    writing-mode: horizontal-tb !important;
}
</style>
{% endblock %}

{% block content %}
<div class="container mt-5">

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show text-center mx-auto w-75" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="閉じる"></button>
            </div>
        {% endfor %}
    {% endif %}

    <h5 class="text-center text-secondary ms-1 mb-4">ユーザー管理</h5>

    <div class="d-flex justify-content-center">
        <div style="width: 100%; max-width: 500px;">
        
            <table class='table table-bordered text-center mt-4'>
                <thead class="table-light">
                    <tr>
                        <th>ユーザー名</th>
                        <th>メールアドレス</th>
                        <th>権限</th>
                        <th>削除</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in team_users %}
                    <tr>
                        <td>{{user.name}}</td>
                        <td>{{user.email}}</td>
                        <td>
                            <form method="POST" action="{% url 'accounts:role_update' user.id %}" 
                                class="d-flex justify-content-between align-items-center" 
                                onsubmit="return confirm('このユーザーの権限を変更しますか？')">
                                {% csrf_token %}
                                <div class="me-2" style="flex-grow: 1;">
                                    <select name="role_id" class="form-select form-select-sm ">
                                        {% for role in roles  %}
                                            <option value="{{ role.id }}" {% if user.role.id == role.id %}selected{% endif %}>
                                            {{ role.role_name }}
                                            </option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <button type ="submit" class="btn btn-sm btn-primary">変更</button>
                            </form>
                        </td>
                        <td>
                            <form method="POST" action="{% url 'accounts:user_delete' user.id %}" onsubmit="return confirm('このユーザーを削除しますか？');">
                                {% csrf_token %}
                                <button class="btn btn-sm btn-danger">削除</button>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <div class="text-start mt-3"> 
                <a href="{% url 'accounts:user_invite' %}" class="btn gray-btn text-dark">
                新規ユーザーを追加
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/user_update.html
{% extends "base.html" %}
{% load add_class %}
{% block content %}
<div class="container mt-5">
    <h5 class="text-center text-secondary ms-1 mb-4">アカウント情報変更</h5>
    <div class="d-flex justify-content-center">
        <div style="width: 100%; max-width: 500px; padding: 30px; border-radius: 10px;">

            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show text-center" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="閉じる"></button>
                    </div>
                {% endfor %}
            {% endif %}

            <form method="POST">
                {% csrf_token %}
                {{ form.non_field_errors}}
                    

                <div class="mb-3">
                    {{ form.name.label }}
                    {{ form.name|add_class:"form-control"}}
                    {% if form.name.errors %}
                        {% for error in form.name.errors %}
                            <div class="text-danger small">{{ error }}</div>
                        {% endfor %}
                    {% endif %}
                </div>

                <div class="mb-3">
                    {{ form.email.label }}
                    {{ form.email|add_class:"form-control"}}
                    {% if form.email.errors %}
                        {% for error in form.email.errors %}
                            <div class="text-danger small">{{ error }}</div>
                        {% endfor %}
                    {% endif %}
                </div>

                <div class="text-center">
                    <button type="submit" class="btn btn-primary px-5">変更</button>
                </div>
            </form>

            <div class="text-center my-4">
                <a href="{% url 'accounts:password_change' %}">パスワードを変更</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}