accounts/urls.py
from django.urls import path
from . import views
from .views import CustomPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('manage', views.user_manage_view, name='user_manage'),
    path('delete/<int:user_id>',views.user_delete_view, name='user_delete' ),
    path('role_update/<int:user_id>',views.user_role_update_view, name='role_update' ),
    path('invite', views.user_invite, name='user_invite'),
    path('invite/register/', views.invite_register_view, name='invite_register'),   
    path('mypage', views.mypage, name='mypage'),
    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
    path('user_update/',views.user_update_view, name='user_update' ),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('shift_pilot/admin/', admin.site.urls),
    path('',include('portfolio.urls')),
    path('shift_pilot/accounts/', include('accounts.urls')),
    path('shift_pilot/shifts/', include('shifts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'portfolio'

urlpatterns = [
    path('', views.index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

shifts/urls.py
from django.urls import path
from . import views

app_name = 'shifts'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('requests/', views.shift_request_view, name='shift_request'),
    path('patterns/', views.shift_pattern_view, name='shift_pattern'),
    path('patterns/delete/<int:pattern_id>/', views.delete_pattern_view, name='delete_pattern'),
    path('pattern_assignment_summaries/', views.pattern_assignment_summary_view, name='pattern_assignment_summaries'),
    path('create/', views.shift_create_view, name='shift_create'),
    path('assign/', views.auto_assign_shifts, name='shifts'),
    path('update-user-shift/', views.update_user_shift, name='update_user_shift'), 
    path("toggle_all_rest/", views.toggle_all_rest, name="toggle_all_rest"),
]

portfolio/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'portfolio/portfolio.html')

templates/portfolio/portfolio.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        .container{
            width:80%;
            margin:0 auto;
        }
        img {
            width: 60%;
            height: auto;
            margin: 10px 0;
        }
        .link{
            font-size: 20px;
            margin: 10px;
            color: blue;

        }
        .link:hover {
            text-decoration: underline !important;
        }
        button{
            display: inline-block;
            font-size: 20px;
            margin: 20px;
            background-color: blue;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;           
        }
    </style>
</head>    
<body>
    <div class="container text-center">
        <h1 class="mt-5">作品No.1 Shift Pilot</h1>
        <img src="{% static 'Shift_Pilot.jpeg' %}" alt="SHIFT PILOTのスクリーンショット">
        <p>ShiftPilotは、公平で効率的なシフト作成を実現するアプリです。</p>
        <p>希望休や勤務条件をもとに、自動で勤務表を作成します。</p>
        <p>従業員ごとの担当回数を見える化し、偏りのないシフトを実現します。</p>
        <p>作成者と従業員の双方にとって、最適なシフト環境を提供します。</p>

        <a href="{% static 'Shift_Pilot_企画書.pdf' %}" class="text-primary text-decoration-none link">企画書</a>
        <a href="{% static 'Shift_Pilot_画面設計図.pdf'%}" class="text-primary text-decoration-none link">画面設計図</a>
        <a href="{% static 'Shift_Pilot_画面遷移図.svg'%}" class="text-primary text-decoration-none link">画面遷移図</a>
        <a href="{% static 'Shift_Pilot_ER図.svg'%}" class="text-primary text-decoration-none link">ER図</a>
        <br><button class="btn btn-primary px-5" onclick="location.href='{% url 'accounts:login' %}'">このアプリにアクセス</button><br>
    </div>
</body>
</html>