accounts/urls.py
from django.urls import path
from . import views
from .views import CustomPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('manage', views.user_manage_view, name='user_manage'),
    path('delete/<int:user_id>',views.user_delete_view, name='user_delete' ),
    path('role_update/<int:user_id>',views.user_role_update_view, name='role_update' ),
    path('invite', views.user_invite, name='user_invite'),
    path('invite/register/', views.invite_register_view, name='invite_register'),   
    path('mypage', views.mypage, name='mypage'),
    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
    path('user_update/',views.user_update_view, name='user_update' ),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('shift_pilot/admin/', admin.site.urls),
    path('',include('portfolio.urls')),
    path('shift_pilot/accounts/', include('accounts.urls')),
    path('shift_pilot/shifts/', include('shifts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'portfolio'

urlpatterns = [
    path('', views.index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

shifts/urls.py
from django.urls import path
from . import views

app_name = 'shifts'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('requests/', views.shift_request_view, name='shift_request'),
    path('patterns/', views.shift_pattern_view, name='shift_pattern'),
    path('patterns/delete/<int:pattern_id>/', views.delete_pattern_view, name='delete_pattern'),
    path('pattern_assignment_summaries/', views.pattern_assignment_summary_view, name='pattern_assignment_summaries'),
    path('create/', views.shift_create_view, name='shift_create'),
    path('assign/', views.auto_assign_shifts, name='shifts'),
    path('update-user-shift/', views.update_user_shift, name='update_user_shift'), 
    path("toggle_all_rest/", views.toggle_all_rest, name="toggle_all_rest"),
]

portfolio/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'portfolio/portfolio.html')

templates/base.html
<!DOCTYPE html>
<html lang='ja'>
    <head>
        <meta charset="utf-8">
        <!--bootstrap-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
        <!--fontawesome-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <style>
        
      a.text-black {
          text-decoration: none;
          transition: text-decoration 0.2s ease;
      }
      a.text-black:hover {
          text-decoration: underline;
      }

      .employee-navbar {
      background-color: #e3f2fd !important;
      }

      .admin-navbar {
        background-color: #2196f3 !important;
      }
      .admin-navbar .nav-link,
      .admin-navbar .navbar-brand{
        color: #fff !important;
      }
      .admin-navbar .dropdown-menu .dropdown-item {
         color: #000 !important; 
      }

       body {
            padding-top: 56px; 
    }
    </style>

        {% block extra_css %}{% endblock %}
    </head>
    <body>

        {% if not hide_navbar %}
        <nav class="navbar navbar-expand-lg 
            {% if request.resolver_match.url_name in 'shift_pattern delete_pattern pattern_assignment_summaries shift_create shifts update_user_shift toggle_all_rest user_manage user_delete role_update user_invite' %}
                admin-navbar
            {% else %}
                employee-navbar
            {% endif %}
            px-3 fixed-top">
            <a class="navbar-brand fw-bold me-4" href="{% url 'shifts:home' %}" style="font-size: 1.5rem;">Shift Pilot</a>

            <div class="collapse navbar-collapse">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shifts:home' %}">ホーム</a>
                    </li>

                    {% if user.is_authenticated and user.role.role_name == '管理者' %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="adminMenu" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            管理者メニュー
                        </a>
                        <ul class="dropdown-menu"> 
                            <li><a class="dropdown-item" href="{% url 'shifts:shift_create' %}">シフト作成</a></li>
                            <li><a class="dropdown-item" href="{% url 'accounts:user_manage' %}">ユーザー管理</a></li>
                        </ul>
                    </li>
                    {% endif %} 

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shifts:shift_request' %}">休み希望申請</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:mypage' %}">マイページ</a>
                    </li>

                    <li class="nav-item">
                        <a class="btn btn-outline-danger ms-2" href="{% url 'accounts:logout' %}">ログアウト</a>
                    </li>

                </ul>
            </div>
        </nav>
        {% endif %}
        {% block content %}
        {% endblock  %}
    </body>
</html>

templates/portfolio.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width", initial-scale=1>
    <style>
        .container{
            width:80%;
            margin:0 auto;
        }
        img {
            width: 60%;
            height: auto;
            margin: 10px 0;
        }
        .link{
            font-size: 20px;
            margin: 10px;
            color: blue;

        }
        button{
            display: inline-block;
            font-size: 20px;
            margin: 20px;
            background-color: blue;
            color: white;
            border: none;           
        }
    </style>
</head>    
<body>
    <div class="container text-center">
        <h1>作品No.1 Shift Pilot</h1>
        <img src="{% static 'SHIFT_PILOT.jpg' %}" alt="SHIFT PILOTのスクリーンショット">
        <p>ShiftPilotは、公平で効率的なシフト作成を実現するアプリです。</p>
        <p>希望休や勤務条件をもとに、自動で勤務表を作成します。</p>
        <p>従業員ごとの担当回数を見える化し、偏りのないシフトを実現します。</p>
        <p>作成者と従業員の双方にとって、最適なシフト環境を提供します。</p>

        {% load static %}
        <a href="{% static 'Shift_Pilot_企画書.pdf' %}" class="link">企画書</a>
        <a href="{% static 'Shift_Pilot_画面遷移図.svg'%}" class="link">画面遷移図</a>
        <a href="{% static 'Shift_Pilot_ER図.svg'%}" class="link">ER図</a>
        <br><button onclick="location.href='/'">このアプリにアクセス</button><br>
    </div>
</body>
</html>